# Generated by Django 5.0.7 on 2024-07-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('profile_image', models.ImageField(upload_to='uploads/%Y/%m/%d')),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
