# Generated by Django 5.0.7 on 2024-07-14 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 14, 14, 53, 27, 592853, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employ',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
